# Generated by Django 4.1.6 on 2023-02-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('nameofcategory', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('deliveryagentid', models.AutoField(primary_key=True, serialize=False)),
                ('nameofdeliveryagent', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'delivery_agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryFirm',
            fields=[
                ('deliveryfirmid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('nameofdeliveryfirm', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'delivery_firm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturerid', models.AutoField(primary_key=True, serialize=False)),
                ('nameofmanufacturer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('dateoforder', models.DateTimeField()),
                ('totalprice', models.IntegerField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('nameofproduct', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, null=True)),
                ('percentage', models.IntegerField()),
            ],
            options={
                'db_table': 'promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shopping_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('stockorderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
            ],
            options={
                'db_table': 'stock_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('userpass', models.CharField(max_length=50)),
                ('nameofuser', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='CompShop.users')),
                ('typeofadmin', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='CompShop.users')),
                ('phonenumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderhasproduct',
            fields=[
                ('quantity', models.IntegerField()),
                ('orderid', models.OneToOneField(db_column='orderid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='CompShop.orders')),
            ],
            options={
                'db_table': 'orderhasproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('productid', models.OneToOneField(db_column='productid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='CompShop.product')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, null=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('productid', models.OneToOneField(db_column='productid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='CompShop.product')),
                ('images', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'product_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productisinsc',
            fields=[
                ('quantity', models.IntegerField()),
                ('productid', models.OneToOneField(db_column='productid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='CompShop.product')),
            ],
            options={
                'db_table': 'productisinsc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productisinsideso',
            fields=[
                ('quantity', models.IntegerField()),
                ('productid', models.OneToOneField(db_column='productid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='CompShop.product')),
            ],
            options={
                'db_table': 'productisinsideso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productisofcategory',
            fields=[
                ('categoryid', models.OneToOneField(db_column='categoryid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='CompShop.category')),
            ],
            options={
                'db_table': 'productisofcategory',
                'managed': False,
            },
        ),
    ]
