# Generated by Django 4.1.6 on 2023-02-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='deliveryagent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='deliveryfirm',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderhasproduct',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productisinsc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productisinsideso',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productisofcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stockorder',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
