# Generated by Django 4.1.6 on 2023-02-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productisinsc',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
