# Generated by Django 4.1.6 on 2023-02-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompShop', '0002_alter_customer_options_alter_deliveryagent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admins',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='deliveryfirmid',
            field=models.ForeignKey(db_column='deliveryfirmid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.deliveryfirm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhasproduct',
            name='productid',
            field=models.ForeignKey(db_column='productid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='adminid',
            field=models.ForeignKey(blank=True, db_column='adminid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.admins'),
        ),
        migrations.AddField(
            model_name='orders',
            name='code',
            field=models.ForeignKey(blank=True, db_column='code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.promotion'),
        ),
        migrations.AddField(
            model_name='orders',
            name='customerid',
            field=models.ForeignKey(db_column='customerid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='deliveryfirmid',
            field=models.ForeignKey(blank=True, db_column='deliveryfirmid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.deliveryfirm'),
        ),
        migrations.AddField(
            model_name='orders',
            name='scid',
            field=models.ForeignKey(db_column='scid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.shoppingcart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='adminid',
            field=models.ForeignKey(db_column='adminid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.admins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturerid',
            field=models.ForeignKey(db_column='manufacturerid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productisinsc',
            name='scid',
            field=models.ForeignKey(db_column='scid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.shoppingcart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productisinsideso',
            name='stockorderid',
            field=models.ForeignKey(db_column='stockorderid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.stockorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productisofcategory',
            name='productid',
            field=models.ForeignKey(db_column='productid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='adminid',
            field=models.ForeignKey(db_column='adminid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.admins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='customerid',
            field=models.ForeignKey(db_column='customerid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockorder',
            name='adminid',
            field=models.ForeignKey(db_column='adminid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.admins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockorder',
            name='manufacturerid',
            field=models.ForeignKey(db_column='manufacturerid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CompShop.manufacturer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderhasproduct',
            unique_together={('orderid', 'productid')},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('productid', 'startdate')},
        ),
        migrations.AlterUniqueTogether(
            name='productimages',
            unique_together={('productid', 'images')},
        ),
        migrations.AlterUniqueTogether(
            name='productisinsc',
            unique_together={('productid', 'scid')},
        ),
        migrations.AlterUniqueTogether(
            name='productisinsideso',
            unique_together={('productid', 'stockorderid')},
        ),
        migrations.AlterUniqueTogether(
            name='productisofcategory',
            unique_together={('categoryid', 'productid')},
        ),
    ]
